name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker build \
            -t afridp/eventbrigadge-client \
            --build-arg VITE_APP_NODE_ENV="production"  \
            --build-arg VITE_APP_SERVER_BASE_URL="${{ secrets.VITE_APP_SERVER_BASE_URL }}" \
            .
      - name: Publish Image to docker hub
        run: docker push afridp/eventbrigadge-client:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull afridp/eventbrigadge-client:latest
      - name: Delete old running container
        run: docker rm -f eventclient-app-container
      - name: run Docker Container
        run: docker run -d -p 3000:80 --name eventclient-app-container afridp/eventbrigadge-client:latest     
